### ISSUE TITLE
PCB assembly

### ISSUE THREAD

**Issue by ituri** [teapotlaboratories/bwlr1e#3]
Hey! 

Interesting project! Do you also provide files for the jlpcb pcb assembly? I'm not particularly skilled at soldering small SMD components, so having jlpcb handle that would be greatly appreciated.

Thanks!
ituri

**Comment by aldwinhermanudin** [comment]
Thanks!

You could order the device (board+assembly) directly from the manufacturer ( PCBWay ) that I'm using through [here](https://link.teapotlabs.io/bwlr1e-order). 

That said, all the necessary file you need for JLCPCB Assembly is available in the repo located at [hardware/main/kicad/production](https://github.com/teapotlaboratories/bwlr1e/tree/main/hardware/main/kicad/production)

Aldwin

**Comment by ituri** [comment]
Amazing, didn't know about that before! Thank you!
